# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-19 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_time', models.DateTimeField(blank=True, null=True)),
                ('pic_path', models.ImageField(upload_to='')),
                ('pic_text', models.TextField()),
            ],
        ),
    ]
