# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_title', models.CharField(blank=True, max_length=40, null=True)),
                ('letter_time', models.DateTimeField(blank=True, null=True)),
                ('letter_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_title', models.CharField(blank=True, max_length=40, null=True)),
                ('pic_time', models.DateTimeField(blank=True, null=True)),
                ('pic_path', models.ImageField(upload_to='images/')),
                ('pic_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
