# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
