# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170519_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
